theme: jekyll-theme-minimal
title: Claire Xin Tong
description: Hi! I am Xin Tong, a master's student in Computational Linguistics at the University of Manchester. 
             I am interested in the interface between human language learning and the learning mechanisms of language models, 
             with an specification in Syntax and Phonetics! Looking forward to communicating with you talented guys!
